added workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,6 +1,6 @@
 name: 01 - Building Blocks
 
-on: workflow_dispatch
+on: push
 
 jobs:
   echo-hello:
@@ -11,9 +11,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest     
     steps:
-      - name: Successful step
-        run: |
-          echo "I will succeed"   
-          exit 0
+      - name: Failed step
+        run: |  
+          echo "I will fail"
+          exit 1
       - name: Say goodbye
         run: echo "Goodbye!"    
